/* lh2_factory_cal.h — GENERATED by utils/calibration/lh2_ootx.py from the base stations'
 * OOTX factory calibration. Do not hand-edit; re-run lh2_ootx.py --header when a
 * base station is replaced. Per plane: {phase, tilt, gibmag, gibphase} [rad]. */
#ifndef LH2_FACTORY_CAL_H
#define LH2_FACTORY_CAL_H

/* BS index 0: uid D1A56BEC, polynomials [8, 9] */
#define LH2_FACTORY_CAL_BS0 { { 0.0f, -0.0474853515625f, -0.0007991790771484375f, 1.7607421875f }, { 0.0003008842468261719f, 0.046173095703125f, -0.0033245086669921875f, 1.279296875f } }

/* BS index 1: uid 66DB72B9, polynomials [20, 21] */
#define LH2_FACTORY_CAL_BS1 { { 0.0f, -0.04656982421875f, 0.005252838134765625f, 0.544921875f }, { 0.0017528533935546875f, 0.0462646484375f, 0.0025386810302734375f, 1.923828125f } }

#endif /* LH2_FACTORY_CAL_H */
