/**
 * @file   main_real.c
 * @brief  LH2 3D Positioning — crossing-beams solver on RP2350, dual-core.
 *
 * Core split (producer / consumer):
 *
 *   Core 1  (capture)  — owns ALL sensor I/O. Initialises all 4 TS4231
 *                        sensors (so every PIO IRQ is routed to core 1) and
 *                        loops db_lh2_process_location() for all 4, filling
 *                        g_lh2[].locations with decoded LFSR positions.
 *
 *   Core 0  (compute)  — reads g_lh2[], decodes angles, runs solve3d, emits
 *                        VISION_POSITION_ESTIMATE over UART0 to the Pixhawk,
 *                        and prints USB diagnostics.
 *
 * Why all init must live on core 1: db_lh2_init() calls irq_set_enabled(),
 * which arms the PIO IRQ on whichever core executes it. Putting all four
 * inits in core1_entry() guarantees every capture IRQ fires on core 1.
 *
 * Pipeline:
 *   lh2/             — PIO+DMA capture (TS4231 → LFSR counts)        [core 1]
 *   angle_decoder/   — LFSR counts → EMA-filtered az/el             [core 0]
 *   cv/ + solve3d/   — fundamental matrix / triangulation           [core 0]
 *   mavlink/         — ODOMETRY (msg #331) over UART0               [core 0]
 *
 * Serial output (USB, 115200):
 *   A,<sensor>,0,<az_deg>,<el_deg>      angle update for lighthouse 0
 *   P,<sensor>,<x>,<y>,<z>              3D point
 *   C,<n>,<cx>,<cy>,<cz>                centroid (also sent as VPE)
 *
 * Hardware pins (data, env):
 *   S0 10/11   S1 12/13   S2 18/19   S3 20/21
 *   MAVLink UART0 TX/RX on GPIO 0/1.
 *
 * @copyright Inria, 2026
 */

#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <string.h>

#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "pico/time.h"
#include "hardware/clocks.h"

#include "lh2/lh2.h"
#include "angle_decoder/angle_decoder.h"
#include "solve3d/solve3d.h"     /* lh2_bs_pose_t, solve3d_calib_run, lh2_point3d_t */
#include "bs_poses_cal.h"        /* BS_POSES[] — generated by calibrate_export.py */
#include "mavlink/mavlink.h"

// ---------------------------------------------------------------------------
// GPIO pin assignments
// ---------------------------------------------------------------------------

#define LH2_0_DATA_PIN  10
#define LH2_0_ENV_PIN   (LH2_0_DATA_PIN + 1)
#define LH2_1_DATA_PIN  12
#define LH2_1_ENV_PIN   (LH2_1_DATA_PIN + 1)
#define LH2_2_DATA_PIN  18
#define LH2_2_ENV_PIN   (LH2_2_DATA_PIN + 1)
#define LH2_3_DATA_PIN  20
#define LH2_3_ENV_PIN   (LH2_3_DATA_PIN + 1)

// ---------------------------------------------------------------------------
// Timing
// ---------------------------------------------------------------------------

/** Diagnostic print interval [µs] — 10 Hz */
#define PRINT_INTERVAL_US  100000ULL

#define Z_OUTPUT_SCALE       0.776446f
#define Z_OUTPUT_OFFSET_M    0.591149f

// ---------------------------------------------------------------------------
// Calibration constants
// (from utils/user_interface/tools/history_calibration.txt, most recent)
// ---------------------------------------------------------------------------

/** BS index 0 → physical BS 4 — calibrated 2026-05-05 */
#define CAL_BS0_A0  0.00315641f
#define CAL_BS0_B0  (-121.7511f)
#define CAL_BS0_A1  0.00307607f
#define CAL_BS0_B1  (-234.6501f)

/** BS index 1 → physical BS 10 — calibrated 2026-05-04 */
#define CAL_BS1_A0  0.00327992f
#define CAL_BS1_B0  (-126.1425f)
#define CAL_BS1_A1  0.00317364f
#define CAL_BS1_B1  (-236.6446f)

static const lh2_cal_t CAL[NUM_BS] = {
    { .A0 = CAL_BS0_A0, .B0 = CAL_BS0_B0, .A1 = CAL_BS0_A1, .B1 = CAL_BS0_B1 },
    { .A0 = CAL_BS1_A0, .B0 = CAL_BS1_B0, .A1 = CAL_BS1_A1, .B1 = CAL_BS1_B1 },
};

// ---------------------------------------------------------------------------
// Shared state (core 1 writes g_lh2, core 0 reads it)
// ---------------------------------------------------------------------------

static db_lh2_t      g_lh2[NUM_SENSORS];
static lh2_angles_t  g_angles[NUM_SENSORS][NUM_BS];

/** Set true by core 1 once all sensors are initialised; gates core 0's loop. */
static volatile bool g_capture_ready = false;

/**
 * Set true by core 0 when the FC first reports a healthy EKF and DO_SET_HOME
 * has been sent.  Read by core 1 (synthetic only) to restart the square walk
 * from corner 0 so the mission begins from a known home.
 */
static volatile bool g_home_set = false;

// ---------------------------------------------------------------------------
// Core 1 — all sensor capture
//
// Two builds of this function exist:
//   - default            : real PIO/DMA capture from 4 TS4231 sensors
//   - -DSYNTHETIC_CAPTURE : no hardware; core 1 fabricates the exact LFSR
//                           counts a real sensor would emit for a body
//                           tracing a 1×1 m square, so the whole dual-core
//                           pipeline can be exercised without sensors.
//                           See SYNTHETIC_CAPTURE.md.
// ---------------------------------------------------------------------------

#ifdef SYNTHETIC_CAPTURE

#define SYN_PI       3.14159265358979323846f
#define SYN_SEG_US   8000000ULL    /* 8 s per square edge          */
#define SYN_TICK_US  20000ULL      /* inject a fresh set every 20 ms (~LH2 rate) */

/* Base-station slot indices in the lh2 array (basestation = polynomial >> 1). */
#define SYN_SLOT_BS0 4u            /* poly 8/9  → slot 4  */
#define SYN_SLOT_BS1 10u           /* poly 20/21 → slot 10 */
#define SYN_POLY_BS0 8u
#define SYN_POLY_BS1 20u

/** Square corners (world frame, z-up), 1×1 m at z = 2 m. */
static const float SYN_CORNERS[4][3] = {
    {0.00f, 0.00f, 2.00f}, {1.00f, 0.00f, 2.00f},
    {1.00f, 1.00f, 2.00f}, {0.00f, 1.00f, 2.00f},
};

/** Sensor offsets on the rigid body [x, y] metres (flat 5×5 cm square). */
static const float SYN_SENSOR_OFF[NUM_SENSORS][2] = {
    {0.000f, 0.000f}, {0.050f, 0.000f}, {0.050f, 0.050f}, {0.000f, 0.050f},
};

/**
 * @brief  Project a world point into a base station's (horiz, vert) angles.
 *
 * local = Rᵀ · (world − origin); then Bitcraze from_cart():
 *   horiz = atan2(y_local, x_local),  vert = atan2(z_local, x_local)
 * (local +X is the boresight).
 */
static void syn_world_to_angles(const lh2_bs_pose_t *bs, const float w[3],
                                float *horiz, float *vert)
{
    float rel[3] = { w[0] - bs->origin[0], w[1] - bs->origin[1], w[2] - bs->origin[2] };

    /* Rᵀ · rel  (columns of R dotted with rel) */
    float xl = bs->R[0][0] * rel[0] + bs->R[1][0] * rel[1] + bs->R[2][0] * rel[2];
    float yl = bs->R[0][1] * rel[0] + bs->R[1][1] * rel[1] + bs->R[2][1] * rel[2];
    float zl = bs->R[0][2] * rel[0] + bs->R[1][2] * rel[1] + bs->R[2][2] * rel[2];

    *horiz = atan2f(yl, xl);
    *vert  = atan2f(zl, xl);
}

/**
 * @brief  Fabricate both sweep slots for one (sensor, base-station) pair.
 *
 * Inverts the Bitcraze (horiz, vert) → V2 sweep-angle mapping, then the linear
 * calibration, so core 0's angle_decoder recovers exactly (horiz, vert):
 *
 *   q  = tan(vert) / sqrt(1 + tan²(horiz))
 *   s0 = horiz − asin(q·tan30) ,  s1 = horiz + asin(q·tan30)
 *   lfsr_sweep = (s_deg − B_sweep) / A_sweep
 */
static void syn_write_bs(int s, uint8_t slot, uint8_t poly,
                         float A0, float B0, float A1, float B1,
                         float horiz, float vert)
{
    float th = tanf(horiz);
    float tv = tanf(vert);
    float q  = tv / sqrtf(1.0f + th * th);
    float dT = asinf(q * TAN_30);

    float s0_deg = (horiz - dT) * (180.0f / SYN_PI);   /* sweep 0 (Bitcraze angle_1) */
    float s1_deg = (horiz + dT) * (180.0f / SYN_PI);   /* sweep 1 (Bitcraze angle_2) */

    uint32_t lfsr0 = (uint32_t)lroundf((s0_deg - B0) / A0);
    uint32_t lfsr1 = (uint32_t)lroundf((s1_deg - B1) / A1);

    g_lh2[s].locations[0][slot].selected_polynomial = poly;
    g_lh2[s].locations[0][slot].lfsr_location        = lfsr0;
    g_lh2[s].data_ready[0][slot]                     = DB_LH2_PROCESSED_DATA_AVAILABLE;

    g_lh2[s].locations[1][slot].selected_polynomial = poly;
    g_lh2[s].locations[1][slot].lfsr_location        = lfsr1;
    g_lh2[s].data_ready[1][slot]                     = DB_LH2_PROCESSED_DATA_AVAILABLE;
}

static void core1_entry(void)
{
    /* No db_lh2_init() — no hardware touched in synthetic mode. */
    g_capture_ready = true;

    uint64_t start_us   = to_us_since_boot(get_absolute_time());
    uint64_t next_us    = start_us;
    bool     home_latch = false;  /* tracks rising edge of g_home_set */

    while (true) {
        uint64_t now_us = to_us_since_boot(get_absolute_time());
        if (now_us < next_us) {
            tight_loop_contents();
            continue;
        }
        next_us += SYN_TICK_US;

        /* When core 0 sets g_home_set for the first time, restart the square
         * from corner 0 so the mission begins from the known home position. */
        if (g_home_set && !home_latch) {
            start_us   = now_us;
            home_latch = true;
        }

        /* Interpolate body position along the current square edge. */
        uint64_t elapsed = now_us - start_us;
        int   seg = (int)((elapsed / SYN_SEG_US) % 4);
        int   nxt = (seg + 1) % 4;
        float t   = (float)(elapsed % SYN_SEG_US) / (float)SYN_SEG_US;
        float bx  = SYN_CORNERS[seg][0] + t * (SYN_CORNERS[nxt][0] - SYN_CORNERS[seg][0]);
        float by  = SYN_CORNERS[seg][1] + t * (SYN_CORNERS[nxt][1] - SYN_CORNERS[seg][1]);
        float bz  = 2.00f;

        for (int s = 0; s < NUM_SENSORS; s++) {
            float w[3] = { bx + SYN_SENSOR_OFF[s][0],
                           by + SYN_SENSOR_OFF[s][1],
                           bz };

            /* Project through the SAME poses the firmware solves with → exact round-trip. */
            float h0, v0, h1, v1;
            syn_world_to_angles(&BS_POSES[0], w, &h0, &v0);
            syn_world_to_angles(&BS_POSES[1], w, &h1, &v1);

            syn_write_bs(s, SYN_SLOT_BS0, SYN_POLY_BS0,
                         CAL_BS0_A0, CAL_BS0_B0, CAL_BS0_A1, CAL_BS0_B1, h0, v0);
            syn_write_bs(s, SYN_SLOT_BS1, SYN_POLY_BS1,
                         CAL_BS1_A0, CAL_BS1_B0, CAL_BS1_A1, CAL_BS1_B1, h1, v1);
        }
    }
}

#else  /* real hardware capture */

static void core1_entry(void)
{
    /* All four inits run here so every PIO IRQ is armed on core 1. */
    db_lh2_init(&g_lh2[0], 0, LH2_0_DATA_PIN, LH2_0_ENV_PIN);
    db_lh2_init(&g_lh2[1], 1, LH2_1_DATA_PIN, LH2_1_ENV_PIN);
    db_lh2_init(&g_lh2[2], 2, LH2_2_DATA_PIN, LH2_2_ENV_PIN);
    db_lh2_init(&g_lh2[3], 3, LH2_3_DATA_PIN, LH2_3_ENV_PIN);

    g_capture_ready = true;

    while (true) {
        for (int s = 0; s < NUM_SENSORS; s++) {
            db_lh2_process_location(&g_lh2[s]);
        }
    }
}

#endif /* SYNTHETIC_CAPTURE */

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static inline float _rad2deg(float rad)
{
    return rad * (180.0f / 3.14159265358979323846f);
}

static inline float _correct_z_for_test(float z)
{
    return (z - Z_OUTPUT_OFFSET_M) / Z_OUTPUT_SCALE;
}

/**
 * @brief  Print per-sensor 3D points + centroid, and return the centroid.
 *
 * @param pts   array of @p n solved points
 * @param n     number of points
 * @param cx,cy,cz  out: centroid (averaged over per-sensor means)
 * @return      number of active sensors contributing to the centroid (0 = none)
 */
static int _print_and_centroid(const lh2_point3d_t *pts, int n,
                               float *cx, float *cy, float *cz)
{
    if (n <= 0) return 0;

    float sensor_x[NUM_SENSORS] = {0};
    float sensor_y[NUM_SENSORS] = {0};
    float sensor_z[NUM_SENSORS] = {0};
    int   sensor_cnt[NUM_SENSORS] = {0};

    for (int i = 0; i < n; i++) {
        int s = pts[i].sensor_id;
        if (s >= 0 && s < NUM_SENSORS) {
            sensor_x[s] += pts[i].xyz[0];
            sensor_y[s] += pts[i].xyz[1];
            sensor_z[s] += pts[i].xyz[2];
            sensor_cnt[s]++;
        }
    }

    float sum_x = 0.0f, sum_y = 0.0f, sum_z = 0.0f;
    int   n_active = 0;

    for (int s = 0; s < NUM_SENSORS; s++) {
        if (sensor_cnt[s] == 0) continue;
        float x = sensor_x[s] / sensor_cnt[s];
        float y = sensor_y[s] / sensor_cnt[s];
        float z = sensor_z[s] / sensor_cnt[s];
        printf("P,%d,%.4f,%.4f,%.4f\n", s, (double)x, (double)y, (double)z);
        sum_x += x; sum_y += y; sum_z += z;
        n_active++;
    }

    if (n_active == 0) return 0;

    *cx = sum_x / n_active;
    *cy = sum_y / n_active;
    *cz = sum_z / n_active;
    printf("C,%d,%.4f,%.4f,%.4f\n", n_active,
           (double)*cx, (double)*cy, (double)*cz);
    return n_active;
}

// ---------------------------------------------------------------------------
// Core 0 — main()
// ---------------------------------------------------------------------------

int main(void)
{
    /* ① Clock + peripherals */
    set_sys_clock_khz(128000, true);
    stdio_init_all();
    printf("DBG1: stdio initialized\n");
    stdio_flush();
    printf("BOOT: LH2 firmware started\n");
    stdio_flush();
    mavlink_init();          /* UART0 GPIO 0/1 @ 115200 → Pixhawk TELEM2 */
    printf("DBG2: MAVLink initialized\n");
    stdio_flush();
    mavlink_request_ekf_stream();  /* ask FC to stream EKF_STATUS_REPORT @ 1 Hz */
    printf("=== LH2 Crossing-Beams 3D Solver (dual-core) ===\n");
#ifdef SYNTHETIC_CAPTURE
    printf("Core 1: SYNTHETIC capture (no sensors, 1x1m square)\n");
#else
    printf("Core 1: capture (4 sensors)  Core 0: solve + MAVLink VPE\n");
#endif

    printf("BS poses: %s\n", BS_POSE_SOURCE);
    printf("Legend: ANG S<sensor> BS<id> h=horiz v=vert [deg]; "
           "P,<sensor>,x,y,z [m]; C,<n>,cx,cy,cz [m]\n");

    /* ② Compute-side init (no sensor I/O here — that lives on core 1) */
    angle_decoder_init(g_angles, CAL);

    /* ③ Launch capture core without blocking the USB diagnostic loop. */
    multicore_launch_core1(core1_entry);
    uint64_t last_debug_us = to_us_since_boot(get_absolute_time());
    printf("Capture core launched.\n");
    stdio_flush();

    /* ④ Compute loop */
    uint64_t last_print_us = 0;
    float    last_cx = 0.0f, last_cy = 0.0f, last_cz = 0.0f;
    float    last_sensor_xyz[NUM_SENSORS][3] = {{0.0f}};
    bool     last_sensor_valid[NUM_SENSORS] = {false};
    uint64_t last_sensor_update_us[NUM_SENSORS] = {0};
    uint64_t last_sensor_log_us[NUM_SENSORS] = {0};

    while (true) {
        uint64_t now_us = to_us_since_boot(get_absolute_time());

        if (now_us - last_debug_us >= 1000000ULL) {
            printf("RUN: main loop\n");
            stdio_flush();
            last_debug_us = now_us;
        }

        /* Drain UART RX every iteration — EKF_STATUS_REPORT arrives at 1 Hz
         * (34-byte frames) so calling this at full loop rate keeps the FIFO empty. */
        mavlink_rx_update();

        /* Decode whatever core 1 has produced since last pass. */
        if (g_capture_ready) {
            angle_decoder_update(g_lh2, g_angles, CAL, now_us);
        }

        /* ── Event-driven: solve + cache centroid, only when fresh data exists ── */
        if (g_capture_ready) {
            lh2_point3d_t pts[NUM_SENSORS];
            int n = solve3d_calib_run(BS_POSES, g_angles, now_us, pts);
            for (int s = 0; s < NUM_SENSORS; s++) last_sensor_valid[s] = false;

            if (n > 0) {
                float sx = 0.0f, sy = 0.0f, sz = 0.0f;
                int   na = 0;
                float acc_x[NUM_SENSORS]={0}, acc_y[NUM_SENSORS]={0}, acc_z[NUM_SENSORS]={0};
                int   cnt[NUM_SENSORS]={0};
                for (int i = 0; i < n; i++) {
                    int s = pts[i].sensor_id;
                    if (s >= 0 && s < NUM_SENSORS) {
                        acc_x[s] += pts[i].xyz[0];
                        acc_y[s] += pts[i].xyz[1];
                        acc_z[s] += pts[i].xyz[2];
                        cnt[s]++;
                    }
                }
                for (int s = 0; s < NUM_SENSORS; s++) {
                    if (!cnt[s]) continue;
                    last_sensor_xyz[s][0] = acc_x[s] / cnt[s];
                    last_sensor_xyz[s][1] = acc_y[s] / cnt[s];
                    last_sensor_xyz[s][2] = acc_z[s] / cnt[s];
                    last_sensor_valid[s] = true;
                    last_sensor_update_us[s] = now_us;
                    sx += last_sensor_xyz[s][0];
                    sy += last_sensor_xyz[s][1];
                    sz += last_sensor_xyz[s][2];
                    na++;
                }
                if (na > 0) {
                    last_cx = sx / na;
                    last_cy = sy / na;
                    last_cz = sz / na;
                }
            }
        }

        /* ── 10 Hz: odometry + EKF home-set (once) + diagnostic prints ──────── */
        if (now_us - last_print_us < PRINT_INTERVAL_US) {
            continue;
        }
        last_print_us = now_us;

        for (int s = 0; s < NUM_SENSORS; s++) {
            if (!last_sensor_valid[s] || last_sensor_update_us[s] == last_sensor_log_us[s] ||
                now_us - last_sensor_update_us[s] > FRESHNESS_US) continue;
            printf("Q,%llu,%d,%.5f,%.5f,%.5f\n",
                   (unsigned long long)last_sensor_update_us[s], s,
                   (double)last_sensor_xyz[s][0],
                   (double)last_sensor_xyz[s][1],
                   (double)last_sensor_xyz[s][2]);
            last_sensor_log_us[s] = last_sensor_update_us[s];
        }

        uint8_t angle_valid_mask = 0u;
        float raw_angles[NUM_SENSORS][NUM_BS][2] = {{{0.0f}}};
        uint16_t angle_age_ms[NUM_SENSORS][NUM_BS];
        for (int s = 0; s < NUM_SENSORS; s++) {
            for (int bs = 0; bs < NUM_BS; bs++) {
            angle_age_ms[s][bs] = UINT16_MAX;
                if (!g_angles[s][bs].valid ||
                    (now_us - g_angles[s][bs].last_update_us) > FRESHNESS_US) {
                    continue;
                }
                angle_valid_mask |= (uint8_t)(1u << (s * NUM_BS + bs));
                raw_angles[s][bs][0] = g_angles[s][bs].raw_horiz;
                raw_angles[s][bs][1] = g_angles[s][bs].raw_vert;
                uint64_t age_ms = (now_us - g_angles[s][bs].last_update_us) / 1000ULL;
                angle_age_ms[s][bs] = (age_ms > UINT16_MAX) ? UINT16_MAX : (uint16_t)age_ms;
            }
        }
        if (angle_valid_mask != 0u) {
            mavlink_send_lh2_angles(mavlink_timesync_corrected_us(now_us),
                                    raw_angles, angle_age_ms, angle_valid_mask);
        }

        /* Send ODOMETRY at 10 Hz with timestamp corrected to FC timebase. */
        if (last_cx != 0.0f || last_cy != 0.0f || last_cz != 0.0f) {
            mavlink_send_odometry(mavlink_timesync_corrected_us(now_us),
                                  last_cx, last_cy, -_correct_z_for_test(last_cz));
        }

        /* Send DO_SET_HOME exactly once — the first time EKF reports healthy.
         * g_home_set latches true so this never fires again, even if EKF
         * later cycles healthy → unhealthy → healthy. */
        if (!g_home_set && mavlink_is_ekf_healthy()) {
            mavlink_send_do_set_home();
            g_home_set = true;
            printf("EKF healthy — home set\n");
        }

        /* Diagnostic angle output for every detected lighthouse. */
        for (int s = 0; s < NUM_SENSORS; s++) {
            if (!angle_decoder_is_fresh(g_angles, s, now_us)) continue;

            for (int bs = 0; bs < NUM_BS; bs++) {
                float horiz = _rad2deg(g_angles[s][bs].ema_horiz);
                float vert = _rad2deg(g_angles[s][bs].ema_vert);

                printf("A,%d,%d,%.2f,%.2f\n", s, bs,
                       (double)horiz, (double)vert);
                printf("ANG S%d | BS%d h=%+7.2f v=%+7.2f deg\n",
                       s, bs, (double)horiz, (double)vert);
            }
        }

        if (last_cx != 0.0f || last_cy != 0.0f || last_cz != 0.0f) {
             printf("C_RAW,%.4f,%.4f,%.4f\n",
                 (double)last_cx, (double)last_cy, (double)last_cz);
            printf("C,%.4f,%.4f,%.4f\n",
                 (double)last_cx, (double)last_cy,
                 (double)_correct_z_for_test(last_cz));
        }
    }

    return 0;   /* unreachable */
}
