/* bs_poses_cal.h — GENERATED by calibrate_export.py. DO NOT hand-edit. */
/*
 * World frame: origin at calibration origin, +X -> x-axis sample, metres.
 * BS-local +X = boresight. R is base-station-local -> world.
 */
#ifndef BS_POSES_CAL_H
#define BS_POSES_CAL_H

#include "solve3d/solve3d.h"   /* lh2_bs_pose_t, NUM_BS */

#define BS_POSE_SOURCE "yaml:lab.yaml"

static const lh2_bs_pose_t BS_POSES[NUM_BS] = {
    {  /* BS0  (poly 8/9,  BS4) */
        .origin = {0.000000f, 0.000000f, 1.500000f},
        .R = { {0.000000f, -1.000000f, 0.000000f},
               {1.000000f, 0.000000f, 0.000000f},
               {0.000000f, 0.000000f, 1.000000f} },
    },
    {  /* BS1  (poly 20/21, BS10) */
        .origin = {1.000000f, 0.000000f, 1.500000f},
        .R = { {0.000000f, -1.000000f, 0.000000f},
               {1.000000f, 0.000000f, 0.000000f},
               {0.000000f, 0.000000f, 1.000000f} },
    },
};

#endif /* BS_POSES_CAL_H */
